package com.github.kivii.grabdoll.core.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.github.kivii.grabdoll.core.bean.DailyRecord;
import com.github.kivii.grabdoll.core.bean.Image;
import com.github.kivii.grabdoll.core.bean.MachineGroup;
import com.github.kivii.grabdoll.core.bean.Organization;
import com.github.kivii.grabdoll.core.bean.Toys;
import com.github.kivii.grabdoll.core.bean.User;

import com.github.kivii.grabdoll.core.dao.DailyRecordDao;
import com.github.kivii.grabdoll.core.dao.ImageDao;
import com.github.kivii.grabdoll.core.dao.MachineGroupDao;
import com.github.kivii.grabdoll.core.dao.OrganizationDao;
import com.github.kivii.grabdoll.core.dao.ToysDao;
import com.github.kivii.grabdoll.core.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dailyRecordDaoConfig;
    private final DaoConfig imageDaoConfig;
    private final DaoConfig machineGroupDaoConfig;
    private final DaoConfig organizationDaoConfig;
    private final DaoConfig toysDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DailyRecordDao dailyRecordDao;
    private final ImageDao imageDao;
    private final MachineGroupDao machineGroupDao;
    private final OrganizationDao organizationDao;
    private final ToysDao toysDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dailyRecordDaoConfig = daoConfigMap.get(DailyRecordDao.class).clone();
        dailyRecordDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(ImageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        machineGroupDaoConfig = daoConfigMap.get(MachineGroupDao.class).clone();
        machineGroupDaoConfig.initIdentityScope(type);

        organizationDaoConfig = daoConfigMap.get(OrganizationDao.class).clone();
        organizationDaoConfig.initIdentityScope(type);

        toysDaoConfig = daoConfigMap.get(ToysDao.class).clone();
        toysDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        dailyRecordDao = new DailyRecordDao(dailyRecordDaoConfig, this);
        imageDao = new ImageDao(imageDaoConfig, this);
        machineGroupDao = new MachineGroupDao(machineGroupDaoConfig, this);
        organizationDao = new OrganizationDao(organizationDaoConfig, this);
        toysDao = new ToysDao(toysDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(DailyRecord.class, dailyRecordDao);
        registerDao(Image.class, imageDao);
        registerDao(MachineGroup.class, machineGroupDao);
        registerDao(Organization.class, organizationDao);
        registerDao(Toys.class, toysDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        dailyRecordDaoConfig.clearIdentityScope();
        imageDaoConfig.clearIdentityScope();
        machineGroupDaoConfig.clearIdentityScope();
        organizationDaoConfig.clearIdentityScope();
        toysDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public DailyRecordDao getDailyRecordDao() {
        return dailyRecordDao;
    }

    public ImageDao getImageDao() {
        return imageDao;
    }

    public MachineGroupDao getMachineGroupDao() {
        return machineGroupDao;
    }

    public OrganizationDao getOrganizationDao() {
        return organizationDao;
    }

    public ToysDao getToysDao() {
        return toysDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
